name: HACS Validation

on:
  push:
    branches:
      - main

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: Validate HACS
        uses: "hacs/action@main"
        with:
          category: "integration"
